version: '3.7'
services:
  hugo:
    build:
      context: .
      target: hugo
    ports:
      - 1313:1313
    volumes:
      - ./content:/www/content
      - ./static:/www/static
      - ./layouts:/www/layouts
      - ./config.toml:/www/config.toml
    command: ["hugo", "server", "--bind", "0.0.0.0", "--buildDrafts", "--buildFuture", "--watch"]