---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: --AWS_REGION--
  version: --EKS_VERSION--
  tags:
    karpenter.sh/discovery: eksworkshop-eksctl

availabilityZones: [--AZA--, --AZB--]

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    roleName: eksworkshop-eksctl-karpenter
    attachPolicyARNs:
    - arn:aws:iam::--AWS_ACCOUNT_ID--:policy/KarpenterControllerPolicy-eksworkshop-eksctl
    roleOnly: true

iamIdentityMappings:
- arn: "arn:aws:iam::--AWS_ACCOUNT_ID--:role/KarpenterNodeRole-eksworkshop-eksctl"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes
- arn: "arn:aws:iam::--AWS_ACCOUNT_ID--:role/TeamRole"
  username: admin
  groups:
  - system:masters

managedNodeGroups:
- amiFamily: AmazonLinux2
  instanceType: m5.large
  name: mng-od-m5large
  desiredCapacity: 2
  maxSize: 3
  minSize: 0
  labels:
    alpha.eksctl.io/cluster-name: eksworkshop-eksctl
    alpha.eksctl.io/nodegroup-name: mng-od-m5large
    intent: control-apps
  tags:
    alpha.eksctl.io/nodegroup-name: mng-od-m5large
    alpha.eksctl.io/nodegroup-type: managed
    k8s.io/cluster-autoscaler/node-template/label/intent: control-apps
  iam:
    withAddonPolicies:
      autoScaler: true
      cloudWatch: true
      albIngress: true
  privateNetworking: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]